### ISSUE TITLE
Typo in M.nrf24_data_available

### ISSUE THREAD

**Issue by mitk0936** [geomatsi/nodemcu-nrf24#1]
On line 232, bits.lshift should be bit.lshift, according to the nodemcu lua docs.
The typo causes the board to enter PANIC mode.

**Comment by geomatsi** [comment]
Hi @mitk0936 
Thanks for bug report. The fix has been pushed to the repository.

Regards,
Sergey

**Comment by geomatsi** [comment]
To: @mitk0936 

Concerning the issues in your experiments. I tested all 4 examples on my WeMos-D1-mini board today. All those examples are still functional on NodeMCU v2.1.0. There might be some issues with 'not enough memory'. That is why I have a minimal firmware configuration. I used luatool to copy files to spiffs and then dofile to run examples:
```
sudo luatool --port /dev/ttyUSBx --bar --baud <your baud rate> --compile  --src test1.lua --dest nrf24.lua

sudo luatool --port /dev/ttyUSBx --bar --baud <your baud rate> --compile  --src test1.lua --dest test1.lua
```

So I suggest you to check your connections and nrf24 settings.

Here are some things to check.

1. Here are my connection on Wemos-d1-mini:
* nRF24 CE pin -> D3
* nRF24 CS pin -> D4
* nRF24 IRQ pin -> D2 (for test4 only)
* nRF24 SCK pin -> D5
* nRF24 MISO pin -> D6
* nRF24 MOSI pin -> D7

2. Power supply
Note that nRF24 needs 3V3 power supply. Though some of its data pins are 5V tolerant, but check the specs since I don't remember details right now. 

3. nRF24 radio settings
Radio settings shall be the same on two nodes:
* channel should be the same
* if you tweak CRC and bitrate in nrf24.lua - they should be the same as well
* send/recv addresses should be the same

**Note that  rx/tx test1..test4 examples do not follow this rule, so you have to modify addresses appropriately if you use those examples on two nodes.**

Check nRF24 specs if you want to play with one receiver and multiple senders. You can send to single addr, but that  may have some reliability issues when you send often. There is a feature called MultiCeiver (see specs 7.7), but its support is not available in this simple library: see TODO in nrf24_set_recv_address. Though you can send multiple clients to the same pipe. 

Hope that helps.

Regards,
Sergey

**Comment by mitk0936** [comment]
The library doesnt throw any error now, the bug is fixed. Thanks for the clarification, but I am still not able to send/receive messages between two esp-12 dev boards.

**Comment by geomatsi** [comment]
To: @mitk0936 
Well, no idea if you have checked all the suggestions above. One more thing though: remember that messge length can't be more than 32 bytes. Could you please also double-check MOSI/MISO connections.

Regards,
Sergey
